### PR TITLE
Fix type 'availaible' => 'available'

### PR DESCRIPTION
**Pull request by zdimension**

### CODE REVIEW

**Review by roblabla — APPROVED** [review]
:rofl: nice catch, dunno how that typo managed to get into so many places. LGTM.

**Review by marysaka — APPROVED** [review]

**Comment by marysaka** [comment]
Could you rebase on top of master?

**Comment by zdimension** [comment]
I rebased

**Comment by roblabla** [comment]
~~Windows~~ Linux and macOS CI are broken for whatever reason. I forced the merge.

Thanks for the contribution, and sorry it took so long 😩

**Pull request merged**
